"""Audit the raw Store Sales competition data and write a Markdown report."""

from __future__ import annotations

from datetime import date
from pathlib import Path
import zipfile

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT / "data" / "raw"
REPORT_PATH = ROOT / "reports" / "data_audit.md"
EXPECTED_FILES = (
    "train.csv",
    "test.csv",
    "sample_submission.csv",
    "stores.csv",
    "oil.csv",
    "holidays_events.csv",
    "transactions.csv",
)


def find_dataset(csv_name: str) -> Path | None:
    """Return a raw CSV or a ZIP archive containing it."""
    direct = RAW_DIR / csv_name
    if direct.exists():
        return direct
    for archive in sorted(RAW_DIR.glob("*.zip")):
        try:
            with zipfile.ZipFile(archive) as zipped:
                if csv_name in {Path(name).name for name in zipped.namelist()}:
                    return archive
        except zipfile.BadZipFile:
            continue
    return None


def read_dataset(path: Path, csv_name: str) -> pd.DataFrame:
    """Read one CSV, including a named member inside a ZIP archive."""
    if path.suffix.lower() != ".zip":
        return pd.read_csv(path)
    with zipfile.ZipFile(path) as zipped:
        member = next(name for name in zipped.namelist() if Path(name).name == csv_name)
        with zipped.open(member) as data:
            return pd.read_csv(data)


def yes_no(value: bool) -> str:
    return "Yes" if bool(value) else "No"


def dataset_summary(name: str, frame: pd.DataFrame, source: Path) -> dict[str, object]:
    dates = pd.to_datetime(frame["date"], errors="coerce") if "date" in frame else None
    return {
        "dataset": name,
        "source": source.name,
        "rows": len(frame),
        "columns": len(frame.columns),
        "column_names": ", ".join(map(str, frame.columns)),
        "dtypes": ", ".join(f"{column}: {dtype}" for column, dtype in frame.dtypes.items()),
        "missing": frame.isna().sum(),
        "duplicates": int(frame.duplicated().sum()),
        "memory_mib": frame.memory_usage(deep=True).sum() / 1024**2,
        "date_min": dates.min().date().isoformat() if dates is not None and dates.notna().any() else None,
        "date_max": dates.max().date().isoformat() if dates is not None and dates.notna().any() else None,
        "unique_dates": int(dates.nunique()) if dates is not None else None,
    }


def add_check(lines: list[str], check: str, result: object, note: str = "") -> None:
    lines.append(f"| {check} | {result} | {note} |")


def build_report(data: dict[str, pd.DataFrame], sources: dict[str, Path]) -> str:
    """Build the audit report from loaded competition datasets."""
    summaries = {name: dataset_summary(name, frame, sources[name]) for name, frame in data.items()}
    lines = [
        "# Raw Data Audit",
        "",
        f"**Audit date:** {date.today().isoformat()}",
        "",
        "This report is generated by `python -m src.audit_data`. It describes the raw competition files without changing or imputing them.",
        "",
        "## 1. Files inspected",
        "",
    ]
    lines.extend(f"- `{name}` (direct CSV or a raw-data archive member)" for name in data)

    lines += ["", "## 2. Dataset dimensions", "", "| Dataset | Rows | Columns | Approx. memory (MiB) | Columns |", "|---|---:|---:|---:|---|"]
    for name, item in summaries.items():
        lines.append(f"| `{name}` | {item['rows']:,} | {item['columns']} | {item['memory_mib']:.2f} | {item['column_names']} |")

    lines += ["", "### Data types", ""]
    lines.extend(f"- **`{name}`:** {item['dtypes']}" for name, item in summaries.items())

    lines += ["", "## 3. Date coverage", "", "| Dataset | Earliest date | Latest date | Unique dates |", "|---|---|---|---:|"]
    for name, item in summaries.items():
        if item["date_min"] is not None:
            lines.append(f"| `{name}` | {item['date_min']} | {item['date_max']} | {item['unique_dates']:,} |")

    lines += ["", "## 4. Missing values", ""]
    for name, item in summaries.items():
        missing = item["missing"]
        nonzero = missing[missing > 0]
        detail = ", ".join(f"`{column}`: {count:,}" for column, count in nonzero.items()) or "None"
        lines.append(f"- **`{name}`:** {detail}")

    lines += ["", "## 5. Duplicate and key checks", "", "| Dataset / key | Result | Note |", "|---|---|---|"]
    for name, item in summaries.items():
        add_check(lines, f"`{name}` exact duplicate rows", f"{item['duplicates']:,}")

    train = data.get("train.csv")
    test = data.get("test.csv")
    sample = data.get("sample_submission.csv")
    stores = data.get("stores.csv")
    oil = data.get("oil.csv")
    holidays = data.get("holidays_events.csv")
    transactions = data.get("transactions.csv")

    required_train = {"id", "date", "store_nbr", "family", "sales", "onpromotion"}
    required_test = required_train - {"sales"}
    if train is not None:
        add_check(lines, "Training main columns present", yes_no(required_train <= set(train.columns)))
        add_check(lines, "Training IDs unique", yes_no(train["id"].is_unique))
        add_check(lines, "Training date/store/family key unique", yes_no(not train.duplicated(["date", "store_nbr", "family"]).any()))
        add_check(lines, "Negative sales values", f"{int((train['sales'] < 0).sum()):,}")
        add_check(lines, "Negative training onpromotion values", f"{int((train['onpromotion'] < 0).sum()):,}")
    if test is not None:
        add_check(lines, "Test main columns present", yes_no(required_test <= set(test.columns)))
        add_check(lines, "Test IDs unique", yes_no(test["id"].is_unique))
        add_check(lines, "Test date/store/family key unique", yes_no(not test.duplicated(["date", "store_nbr", "family"]).any()))
        add_check(lines, "Negative test onpromotion values", f"{int((test['onpromotion'] < 0).sum()):,}")
    if train is not None and test is not None:
        train_end = pd.to_datetime(train["date"]).max()
        test_dates = pd.to_datetime(test["date"])
        add_check(lines, "Test starts after training ends", yes_no(test_dates.min() > train_end), f"Train ends {train_end.date()}; test starts {test_dates.min().date()}")
        add_check(lines, "Test forecasting horizon", f"{test_dates.nunique()} days", f"Through {test_dates.max().date()}")
        add_check(lines, "Train/test stores match", yes_no(set(train["store_nbr"]) == set(test["store_nbr"])), f"{train['store_nbr'].nunique()} train; {test['store_nbr'].nunique()} test")
        add_check(lines, "Train/test product families match", yes_no(set(train["family"]) == set(test["family"])), f"{train['family'].nunique()} train; {test['family'].nunique()} test")
    if sample is not None and test is not None:
        add_check(lines, "Sample row count matches test", yes_no(len(sample) == len(test)), f"{len(sample):,} rows")
        add_check(lines, "Sample IDs match test IDs in order", yes_no(sample["id"].equals(test["id"])))
        add_check(lines, "Sample prediction column `sales` exists", yes_no("sales" in sample.columns))
    if stores is not None:
        add_check(lines, "Stores `store_nbr` unique", yes_no(stores["store_nbr"].is_unique))
        used = set()
        if train is not None:
            used |= set(train["store_nbr"])
        if test is not None:
            used |= set(test["store_nbr"])
        add_check(lines, "All used stores appear in stores.csv", yes_no(used <= set(stores["store_nbr"])))
    if oil is not None:
        oil_dates = pd.to_datetime(oil["date"])
        add_check(lines, "Oil missing prices", f"{int(oil['dcoilwtico'].isna().sum()):,}", "Not imputed in Stage 1")
        add_check(lines, "Oil duplicate dates", f"{int(oil_dates.duplicated().sum()):,}")
        if train is not None and test is not None:
            all_dates = pd.concat([pd.to_datetime(train["date"]), pd.to_datetime(test["date"])])
            covers = oil_dates.min() <= all_dates.min() and oil_dates.max() >= all_dates.max()
            add_check(lines, "Oil range covers train/test endpoints", yes_no(covers), f"Oil: {oil_dates.min().date()} to {oil_dates.max().date()}; weekday-only observations create date gaps")
    if holidays is not None:
        add_check(lines, "Holiday duplicate dates", f"{int(holidays['date'].duplicated().sum()):,}", "Multiple records on one date can be valid for different locales or events")
        add_check(lines, "Holiday exact duplicate rows", f"{int(holidays.duplicated().sum()):,}")
        add_check(lines, "Rows with `transferred = True`", f"{int(holidays['transferred'].fillna(False).astype(bool).sum()):,}")
        add_check(lines, "Records with type `Transfer`", f"{int(holidays['type'].eq('Transfer').sum()):,}")
        locale_counts = holidays["locale"].value_counts()
        add_check(lines, "Holiday locale counts", "; ".join(f"{key}: {value:,}" for key, value in locale_counts.items()))
    if transactions is not None:
        add_check(lines, "Transactions date/store key unique", yes_no(not transactions.duplicated(["date", "store_nbr"]).any()))
        add_check(lines, "Transaction missing values", f"{int(transactions.isna().sum().sum()):,}")
        add_check(lines, "Negative transaction values", f"{int((transactions['transactions'] < 0).sum()):,}")
        if train is not None:
            tx_dates, tx_stores = set(transactions["date"]), set(transactions["store_nbr"])
            train_dates, train_stores = set(train["date"]), set(train["store_nbr"])
            missing_dates = sorted(train_dates - tx_dates)
            missing_stores = sorted(train_stores - tx_stores)
            date_note = ", ".join(missing_dates) if missing_dates else "None"
            store_note = ", ".join(map(str, missing_stores)) if missing_stores else "None"
            add_check(lines, "Train dates without any transactions row", f"{len(missing_dates):,}", f"{date_note}; absence is not treated as zero")
            add_check(lines, "Train stores without any transactions row", f"{len(missing_stores):,}", store_note)

    lines += ["", "## 6. Cross-file consistency and concise category counts", ""]
    if train is not None:
        lines.append(f"- Stores in training: **{train['store_nbr'].nunique():,}**; product families: **{train['family'].nunique():,}**.")
    if stores is not None:
        lines.append(f"- Store metadata: **{stores['city'].nunique():,}** cities, **{stores['state'].nunique():,}** states, **{stores['type'].nunique():,}** types, and **{stores['cluster'].nunique():,}** clusters.")
    if holidays is not None:
        holiday_types = holidays["type"].value_counts()
        lines.append("- Holiday types: " + ", ".join(f"**{name}** {count:,}" for name, count in holiday_types.items()) + ".")
        locale_counts = holidays["locale"].value_counts()
        lines.append("- Holiday locales: " + ", ".join(f"**{name}** {count:,}" for name, count in locale_counts.items()) + ".")

    lines += [
        "",
        "## 7. Main data relationships",
        "",
        "- Join train/test to stores on `store_nbr`.",
        "- Join train/test to oil on `date`; oil is observed on business days and contains missing prices, so later handling must be explicit.",
        "- Relate holidays by `date` and then by locale information. National holidays can apply broadly, while regional and local holidays must be matched to each store's state or city. A date-only merge can duplicate rows or apply holidays to the wrong stores.",
        "- Join training observations to transactions on `date` and `store_nbr`. Transactions are historical only and must not be invented for the test period.",
        "",
        "## 8. Important competition-specific observations",
        "",
        "- The forecasting unit is one `date` / `store_nbr` / `family` combination.",
        "- The test period follows the training period and contains a 16-day horizon.",
        "- Train and test use the same store and product-family sets, and the sample submission aligns with test IDs.",
        "- Missing oil prices are retained. No imputation is performed in this stage.",
        "- Several holiday records can legitimately share a date. These are not automatically invalid duplicates because locale, type, and description can differ.",
        "- Transaction coverage is historical and incomplete at the date/store level; missing records should be interpreted carefully rather than automatically converted to zero.",
        "",
        "## 9. Issues for later stages",
        "",
        "- Decide on a transparent method for handling missing and non-daily oil prices.",
        "- Design locale-aware holiday processing, including transferred holidays and `Transfer` records.",
        "- Investigate dates and store/date combinations without transaction records before using transactions in analysis.",
        "- Preserve time order and avoid information from the test period when later constructing validation data.",
        "",
        "## 10. Conclusion",
        "",
        "The raw files are structurally consistent and ready for exploratory analysis. The known oil, holiday, and transaction coverage issues are documented and should be handled explicitly in later stages. No raw values were changed during this audit.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    """Load all available raw files, print a summary, and write the report."""
    if not RAW_DIR.exists():
        raise FileNotFoundError(f"Raw data directory not found: {RAW_DIR}")

    data: dict[str, pd.DataFrame] = {}
    sources: dict[str, Path] = {}
    print(f"Auditing raw data in {RAW_DIR}")
    for csv_name in EXPECTED_FILES:
        source = find_dataset(csv_name)
        if source is None:
            print(f"[missing] {csv_name}")
            continue
        try:
            frame = read_dataset(source, csv_name)
        except (OSError, ValueError, KeyError, zipfile.BadZipFile) as exc:
            print(f"[error] {csv_name}: {exc}")
            continue
        data[csv_name] = frame
        sources[csv_name] = source
        print(f"[ok] {csv_name}: {len(frame):,} rows x {len(frame.columns)} columns (source: {source.name})")

    if not data:
        raise RuntimeError("No supported raw competition files could be read.")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(build_report(data, sources), encoding="utf-8")
    print(f"Audit complete: {REPORT_PATH}")


if __name__ == "__main__":
    main()

